#!/usr/bin/env ruby
# encoding: utf-8

config_paths = %w(. config tmp).map { |dir| dir + '/fromage.yml' }

config_file = config_paths.find(&File.method(:exists?))

if config_file
  require 'yaml'

  config = YAML.load_file config_file

  def subset_to_s(subset)
    "foreman start -m #{subset.map { |x, y| "#{x}=#{y}" }.join(',')}"
  end

  subset_index = ARGV[0] ? ARGV[0].to_i : config['default_subset']
  subset = config['subsets'][subset_index]

  if subset
    string_to_execute = subset_to_s(subset)

    puts "running `#{string_to_execute}`..."
    exec string_to_execute
  else
    available_subsets = config['subsets'].map.each_with_index do |s, i|
      " #{config['default_subset'] == i ? '*' : ' '}#{i}  #{subset_to_s(s)}"
    end

    puts 'available subsets:'
    puts available_subsets
    exit 1
  end
else
  puts "configuration file not found (#{config_paths.join(', ')})"
  exit 1
end
