#!/usr/bin/env ruby
# encoding: utf-8

require "yaml"

def subset_to_s(subset)
  subset.map { |x,y| "#{x}=#{y}" }.join(",")
end

subsets = YAML.load(open "tmp/föremål.yml")

if subset = subsets[ARGV[0].to_i || 0]
  string_to_execute = "foreman start -m #{subset_to_s(subset)}"
  puts "running #{string_to_execute}..."
  exec string_to_execute
else
  puts "available subsets:"
  subsets.each_with_index { |s, i| puts "  #{i}:  #{subset_to_s(s)}" }
end
